---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: mqtt-publisher-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: primeroz.xyz/v1
    resource: mqttpublishers
    revisionHistory:
      fieldPaths:
      - spec.topicName
  childResources:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: InPlace
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://mqtt-controller.metacontroller/sync-mqtt-publisher
