resources:
- v1/crdv1.yaml
- manifests/mqttControllerDeployment.yaml
- manifests/mqttControllerService.yaml
- manifests/mqttPublisherCompositeController.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: primeroz/jsonnetd-mqtt-controller
  newTag: v0.18
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value: "--print-requests"
  target:
    group: apps
    kind: Deployment
    name: mqtt-controller
    version: v1
