resources:
- v1/crdv1.yaml
- manifests/mqttControllerDeployment.yaml
- manifests/mqttControllerService.yaml
- manifests/mqttPublisherCompositeController.yaml
- manifests/mqttSubscriberCompositeController.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: primeroz/jsonnetd-mqtt-controller
  newTag: v0.40
