resources:
- v1/crdv1.yaml
- manifests/randomSecretsCompositeController.yaml
- manifests/randomSecretsControllerDeployment.yaml
- manifests/randomSecretsControllerService.yaml
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value: "--print-requests"
  target:
    group: apps
    kind: Deployment
    name: random-secrets-controller
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: primeroz/jsonnetd-random-secrets-controller
  newTag: "0.6"
