---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-secrets-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-secrets-controller
  template:
    metadata:
      labels:
        app: random-secrets-controller
    spec:
      containers:
      - name: hooks
        image: primeroz/jsonnetd:0.3
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: random-secrets-hooks
